### ISSUE TITLE
Not a comment for comment 10 - missing #

### ISSUE THREAD

**Issue by siprbaum** [tacdevel/slncommenttest#1]
Stumbled on this via the msbuild issue about comments in solutions.
Looks like you forogt to a `#` to make this an actual comment
https://github.com/tacdevel/slncommenttest/blob/cf7905b3351b39980d3d4cbe2d06dfdec5bd45b5/SlnCommentTest.sln#L27

**Comment by tacdevel** [comment]
Whoops. Thanks for catching that. It should be fixed in a minute or so.
